### ISSUE TITLE
ERROR: Failed to precompile TriangularMatrices

### ISSUE THREAD

**Issue by AndishehDadashi** [chriselrod/TriangularMatrices.jl#1]
Hello, I'm pretty new to Julia. 

I am trying to use the examples you have here. It seems I could install this package but I get an error while I am using it. Besides, julia doesn't recognize srandmat. 
I get these of errors while performing your example;
1. LoadError: UndefVarError: scale! not defined
2. ERROR: Failed to precompile TriangularMatrices 
3. UndefVarError: srandmat not defined

Do I need to install any other packages before using TriangularMatrices?

**Comment by chriselrod** [comment]
Hi, I haven't updated this package in a long time.

What are you looking to do in particular?

**Comment by AndishehDadashi** [comment]
I just was interested in the example you had there. I would like to work on the matrix multiplication using any library/package in Julia to observe the program's performance. Your example and the package you are using seemed much easier for me rather than using the BLAS library.

**Comment by chriselrod** [comment]
This package used a weird memory layout, which should help performance, but the kernels and many of the implementation details are suboptimal. So it'd take some work to get it up to speed.

A few things you may want to take a look at:

BLIS style GEMM demo by Sacha:
https://github.com/Sacha0/GemmDemo.jl
JuliaBLAS organization, by YingboMa and myself:
https://github.com/JuliaBLAS
It contains an attempt by YingboMa, and one by myself.
Unfortuantely, it's been about half a year since either of us had the time to work on them.

More recently, I've been working on:
https://github.com/chriselrod/PaddedMatrices.jl
but I have been focusing on smaller matrices, where BLAS is slow.
My short term plan (which I haven't gotten around to doing yet), is to simply dispatch to BLAS/LAPACK for operations on "big" matrices. Then these can be replaced with Julia functions as they get written.

How familiar are you with
1. Julia?
2. Metaprogramming more generally?
3. Matrix multiplication?

I have written brief introductions [here](https://bayeswatch.org/2018/08/08/matrix-multiplication-kernel/) and [here](https://bayeswatch.org/2018/08/14/simdarrays-fast-single-threaded-matrix-multiplication-for-small-and-moderate-sizes/).
My basic approach has been to define a custom array type that has columns "padded" so that they are an integer multiple of SIMD vector width. That is, a 3x3 matrix will be a 4x3 matrix under the hood, with the last row hidden.
This gives better performance, and also makes our job easier.

Matrix multiplication is performed blockwise, by repeatedly applying an optimized kernel. As described in my links, that kernel is designed to maximize the number of floating point operations (specifically, fused multiply add instructions) relative to the amount of instructions moving memory in and out of registers (and the kernel's size is thus constrained by the size and number of registers).

For the [kernels](https://github.com/JuliaBLAS/jBLAS.jl/blob/master/src/kernels.jl), I've been using generated functions to construct fairly optimal kernels for the specific host computer (ie, using the specific size and number of registers).

Getting the kernel down is the easy part. The hard part is actually applying that kernel, to scale things up to big matrices.
If you're computing D = A * X, where A is M x N, and X is N x P, matrix multiplication should theoretically take O(m*n*p) time. It is hard to achieve this in practice, because beyond m,n,p = 200 or so, they begin slowing down dramatically due to cache missed. That is, the CPU simply sits idle, waiting for memory, instead of computing.
The Julia kernels appear just as fast as those from the big BLAS library. If it were possible to scale them up assuming O(m*n*p), these Julia BLAS libraries would be as fast or faster than OpenBLAS/BLIS/MKL for single threaded applications. Unfortunately, that is not possible.

To multiply big matrices, you need "packing". Sacha0 and YingboMa's implementations do this, but mine do not.
Without packing, as soon as the three matrices (the two being multiplied, and their product) are big enough to bust the L2 cache, performance suffers.
I experimented with prefetching as an alternative work around, but hadn't gotten around to really testing it (preliminary results showed some improvement).

This is further complicated by the fact it seems architecture dependent. But unlike the kernels, it doesn't seem obvious to me how to translate any hardware queries to strategies (but I did try to use L1,L2, and L3 cache sizes to determine blocking patterns).

There is a lot of performance left on the table here. If you'd like to analyze the performance of matrix multiplication in Julia, odds are you'll find a lot that can be improved (and hopefully how)!

Let me know if you have any questions.

**Comment by AndishehDadashi** [comment]
Thank you very much for your detailed explanation. These are everything went through my mind and now I have a better understanding. As I mentioned, I am not that familiar with Julia, just started to learn and planning to learn more. Also, thank you for the links I will read them as well.
